name: News Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
    - name: Setup Java JDK
      uses: actions/setup-java@v3.0.0
      with:
        java-version: 1.8
    - run: npm ci
      working-directory: ./frontend
    - run: npm run build --if-present
      working-directory: ./frontend
      
    - name: copy react to spring static resources
      run: 
        mkdir -p backend/src/main/resources/static
        cp -a frontend/build/. backend/src/main/resources/static/
        
    - name: build spring
      run: mvn -B package --file pom.xml
      working-directory: ./backend
      
